### ISSUE TITLE
安卓登录后闪退

### ISSUE THREAD

**Issue by fanyuecheng** [niuhuan/pikapi-flutter#1]
Red Mi K30s 至尊
MIUI 12.5.1

**Comment by zhongfly** [comment]
同样的情况…希望能解决

**Comment by niuhuan** [comment]
已经修复了 @zhongfly  @fanyuecheng  可以下载release 1.0.1

**Comment by zhongfly** [comment]
> 已经修复了 @zhongfly @fanyuecheng 可以下载release 1.0.1

确实不闪退了
