### ISSUE TITLE
很实用不过有一两个问题

### ISSUE THREAD

**Issue by LegenSWare** [niuhuan/pikapi-flutter#10]
在线游览时图片清晰度很低，设置里选项“浏览时图片质量”改了无效。
![Screenshot_20210818-093917](https://user-images.githubusercontent.com/89114046/129822838-82b97b17-fd3a-4041-b2cc-eaa2433a691a.png)

还有在
![2021_08_18_09_40_02](https://user-images.githubusercontent.com/89114046/129822941-0e20bd5f-c815-435d-a3b7-e0d54e34ca94.jpg)
这样的界面无法找到上传者

还有这个界面
![Screenshot_20210818-094327_1](https://user-images.githubusercontent.com/89114046/129823429-9cd066da-eeca-435b-b6a0-236ac0223247.png)
那4个问号看着不是很舒服，如果可以的话希望能添加一个自定义的功能

下载解压之后的图片因为没有文件后缀（.jpg .png）没法直接打开

最后希望您的pika第三方客户端做得更好 （安卓端）#

**Comment by zhongfly** [comment]
"无法找到上传者"
你应该下载最新版本

**Comment by niuhuan** [comment]
清晰度的问题可以下最新版再设置原图试试。

**Comment by niuhuan** [comment]
文件没有拓展名(.jpg .png), 是为了相册程序扫描到图片, 可以直接更名为.jpg使用。以后或许会做成可选项项。

**Comment by zhongfly** [comment]
> 文件没有拓展名(.jpg .png), 是为了相册程序扫描到图片, 可以直接更名为.jpg使用。以后或许会做成可选项项。

安卓有个潜规则，在文件夹内添加.nomedia文件后，相册就不会扫描文件夹（部分相册/图库app可能不理会）
