### ISSUE TITLE
虚拟机内无法运行

### ISSUE THREAD

**Issue by resticDOG** [niuhuan/pikapi-flutter#13]
OS: Windows 10 (1809 OS build 17763.720)
虚拟机运行的win10, 在虚拟机运行打开exe毫无反应, 不知是不是虚拟机的图形api不足以运行

**Comment by resticDOG** [comment]
补充一下: pve是基于QEMU

**Comment by niuhuan** [comment]
虚拟机内运行库, 显卡驱动, DX 都装好了的话, 我也束手无策了。您可以往flutter提交isuse

https://github.com/go-flutter-desktop/go-flutter
https://github.com/flutter/flutter
