### ISSUE TITLE
请问什么时候能支持评论？

### ISSUE THREAD

**Issue by zhongfly** [niuhuan/pikapi-flutter#17]
目前只有看评论的功能，发评论功能在pica-golang也实现了，不知道什么时候在这里用上呢？
另外，子评论目前支持了吗？

**Comment by niuhuan** [comment]
评论和回复嘛，不知道怎么弄可以好看一点

**Comment by niuhuan** [comment]
🤣 有点懒就一直没弄

**Comment by zhongfly** [comment]
有计划就行

niuhuan ***@***.***> 于 2021年9月4日周六 23:38写道：

**Comment by niuhuan** [comment]
评论功能我加上了, 你可以看一下评论之后有没有清除缓存, 哔咔评论后就不能删除, 有点洁癖所以一直不想做这个功能

**Comment by zhongfly** [comment]
> 评论功能我加上了, 你可以看一下评论之后有没有清除缓存, 哔咔评论后就不能删除, 有点洁癖所以一直不想做这个功能

能否可以用左右滑动来在章节和评论页面间切换：当处于章节页面时，从右往左滑进入“评论”页面，再从左往右滑动回到“章节”？

**Comment by zhongfly** [comment]
> 评论和回复嘛，不知道怎么弄可以好看一点

评论的话，参考哔咔，评论输入框一直悬浮在屏幕最底端，并且点击每一个楼层右下角的子回复展开，就可以对这个评论发表子回复。

另外，pika还没实现子回复的阅读/发表

**Comment by niuhuan** [comment]
做成tab才能左右滑动，但是那样需要将tab页变成固定高度，内容变成滚动，和全局的滚动冲突。固定顶部的卡片，tag多了可视区域变得更少。

**Comment by zhongfly** [comment]
> 你先自己build一下试试评论和子评论的功能有没有问题

功能的确是有了…像子评论应该在对应的回复处显示出它有多少子回复，不然根本不知道它有还是没有子评论，而且最好是在当前页面展开

**Comment by niuhuan** [comment]
有啊, 只有有回复的才会有回复数标识

**Comment by zhongfly** [comment]
> 有啊, 只有有回复的才会有回复数标识

好的
我觉得悬浮于底部的输入框会更好一些。

**Comment by niuhuan** [comment]
有时候内容比较长, 详情页tab是超出屏幕的, 尤其是1080P或者以下的手机。

你的这个想法, 既要悬浮, 还要左右切换, 同时满足这两个需求, 那么最好的是TAB吸顶效果, 并且TAB展示出来以后, 才出现悬浮窗。

只有大概思路, 还没计划做。

**Comment by niuhuan** [comment]
你如果测试上功能没有问题, 我再加一些功能之后会release一个包。

**Comment by zhongfly** [comment]
听起来是这样的，我也是以平常用到的一些app体验来说的。

niuhuan ***@***.***> 于 2021年9月7日周二 20:02写道：

**Comment by zhongfly** [comment]
> 你如果测试上功能没有问题, 我再加一些功能之后会release一个包。

有一个小问题，发了一条子评论后，子评论数不变(比如应该从3变成4)，就算推出这个漫画再打开评论，数字也没有变化。这大概是缓存了？
只有再发一个普通评论才会自动更新评论数据

**Comment by zhongfly** [comment]
另外就是评论的点赞功能，这个优先级倒不大。

**Comment by niuhuan** [comment]
有一个小问题，发了一条子评论后，子评论数不变(比如应该从3变成4)， (我有清掉缓存, 但是非子评论列表页没有刷新, 评论对象是直接带过去的) 大概就是这样吧

**Comment by aaaly666** [comment]
> 目前只有看评论的功能，发评论功能在pica-golang也实现了，不知道什么时候在这里用上呢？ 另外，子评论目前支持了吗？

大佬可否留下联系方式，以便问问题
