### ISSUE TITLE
安卓无法登录

### ISSUE THREAD

**Issue by zhangjuzuo** [niuhuan/pikapi-flutter#18]
账号和密码确认无误了，在官方客户端可以登录，但是在这个app没办法登录。
配置是
账号
密码
分流1
代理服务器未设置
点右上角保存后弹窗提示请检查账号密码

**Comment by niuhuan** [comment]
您可以在官方APP中点开编辑查看账号，使用账号登录。
手机号或email，也可以试一下。

或者试试简单的密码。

不知道您的账号是否有中文。

问题没有解决前。可以注册一个账号体验一下。

**Comment by niuhuan** [comment]
@zhongfly

**Comment by zhongfly** [comment]
我测试了最新代码。推出账号后重新登录，可以登录。

ps我的用户名是全英文

**Comment by zhangjuzuo** [comment]
我尝试注册的时候报错了 错误信息是
PlatfromException(, invalid character '<' looking for begining of value, , null)
我把表单的信息全填了 除了代理服务器没设置外其他都设置了 账号也是英文
另外我的哔咔账号也是英文的 检查了之后也没发现问题
手机是meizu x8 系统版本是Android 8.1.0

**Comment by niuhuan** [comment]
切换分流试一下 ，代理设置不用设置 。

invalid character '<' looking for begining of value, , null

是因为官方代理时常被玩坏

**Comment by zhangjuzuo** [comment]
或者你们是否愿意帮我测试一下？我可以私发账号和密码给你们试一下能否登录，我试了一下不管是我用不用v2ray都登录不了，分流1和2都提示不能登录，3提示网络不通

**Comment by zhangjuzuo** [comment]
zhangjuzuo1996@gmail.com

**Comment by niuhuan** [comment]
给你发了一封邮件

**Comment by niuhuan** [comment]
测试结果已经用邮箱发送，无代理正常登录。
