### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by Z-fly** [niuhuan/pikapi-flutter#19]
![image](https://user-images.githubusercontent.com/10470892/132946728-841bb16b-f216-4987-a8e9-a5ec1d1706fc.png)
提供一个解除封印的功能，可以设置一个按钮，点击解除，再次点击封印。

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/132948533-131b6286-cf0b-44e3-a79c-381c32c238bc.png)
点击头像后像哔咔那样可以放大头像，并提供另存为功能

**Comment by zhongfly** [comment]
默认全屏选项里已经有了啊

**Comment by Z-fly** [comment]
> 默认全屏选项里已经有了啊
才发现有个默认全屏选项

**Comment by Z-fly** [comment]
@niuhuan mac上头像保存功能是不是没法实现了。手机上确实可以了

**Comment by niuhuan** [comment]
> @niuhuan mac上头像保存功能是不是没法实现了。手机上确实可以了

能, 你去releases下载就行了, 上午一直在调开发环境。 囧。

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/133064275-cb2ba8f5-a60b-4a28-95ac-df9e082c6c30.png)
这个一打开就闪退

**Comment by Z-fly** [comment]
在启动台里打开就闪退了
![image](https://user-images.githubusercontent.com/10470892/133064346-f12dda06-6012-4fca-92ab-2b57744b0708.png)

**Comment by niuhuan** [comment]
我这里没有问题, 你可以尝试, 把旧的删了拖进去新的
