### ISSUE TITLE
[Feature request]漫画详情页面的一些建议

### ISSUE THREAD

**Issue by zhongfly** [niuhuan/pikapi-flutter#2]
1. 漫画详情页面上有各类tag，在官方版中这些tag都可以点击，可以查看到该tag下的所有漫画
2. 显示漫画的上传/更新时间
3. 保存阅读进度，增加”继续阅读“的功能，阅读到xx话xx页
4. 点击作者名称可以跳转到搜索作者

**Comment by niuhuan** [comment]
@zhongfly tag可以点击了 官方app中, 点击tag后默认排序是like最多.

**Comment by niuhuan** [comment]
这些功能都已经完成了
