### ISSUE TITLE
添加音量键翻页

### ISSUE THREAD

**Issue by Ipmlosion** [niuhuan/pikapi-flutter#20]

**Comment by niuhuan** [comment]
请您耐心等待，正在研究安卓硬件按钮监控

**Comment by Fireblossom** [comment]
音量键翻页会在漫画页更改方向/阅读器之后失效。
以及相册模式/PC能不能支持翻页呢？

**Comment by niuhuan** [comment]
> 音量键翻页会在漫画页更改方向/阅读器之后失效。
> 以及相册模式/PC能不能支持翻页呢？

好的，谢谢反馈。时间会比较长，需要耐心等待。

**Comment by niuhuan** [comment]
PC端可以使用上下控制翻页了, 不过需要额外从设置里操作一下。
相册模式也支持翻页了。
手机的BUG也修复了。
