### ISSUE TITLE
窗口缩放比例固定

### ISSUE THREAD

**Issue by Z-fly** [niuhuan/pikapi-flutter#22]
提供个选项，锁定下缩放比例，现在是任意调整窗口大小，然后图片就会跟着拉伸

**Comment by Z-fly** [comment]
我刚刚看了下，好像并没有拉伸

**Comment by niuhuan** [comment]
你松手才会重新渲染, 都是等比所放的

**Comment by niuhuan** [comment]
> win和mac的缩放不一致。我总感觉win是把图片按窗口大小拉伸了 mac全屏的效果和win全屏的效果你那边看一样吗？

我感觉差不多，你把缩放比例调成 100%
