### ISSUE TITLE
[Feature Request]加载失败后自动重试，更改下拉重试为点击屏幕重试

### ISSUE THREAD

**Issue by zhongfly** [niuhuan/pikapi-flutter#24]
由于有时出现打开漫画失败的情况，希望增加自动重试。
同时下拉重试便捷性可能还略逊于直接点击屏幕任意位置重试，有时需要频繁重试时更是如此。

**Comment by niuhuan** [comment]
失败下拉刷新换点击刷新改动会更加方便

重试我觉得可以调试一些参数

		client.Transport = &http.Transport{
			TLSHandshakeTimeout:   time.Second * 10,
			ExpectContinueTimeout: time.Second * 10,
			ResponseHeaderTimeout: time.Second * 10,
			IdleConnTimeout:       time.Second * 10,
			DialContext:           &net.Dialer{
                         	Timeout:   30 * time.Second,
                          	KeepAlive: 30 * time.Second,
},
		}

**Comment by niuhuan** [comment]
点击刷新的功能放在设置里了
