### ISSUE TITLE
【BUG】mac 闪退

### ISSUE THREAD

**Issue by Z-fly** [niuhuan/pikapi-flutter#25]
https://user-images.githubusercontent.com/10470892/133185812-0f5d49f2-0914-4004-8075-56e38c8b398e.mp4

删除了主程序和Library/Application Support/pikapi/后还是会闪退

**Comment by niuhuan** [comment]
大佬如果你1.0.16-fix可以用就先用吧。

**Comment by niuhuan** [comment]
我装了一个13的虚拟机要卡死了

**Comment by Z-fly** [comment]
> 我装了一个13的虚拟机要卡死了

我可以给你10.8的虚拟机镜像

**Comment by niuhuan** [comment]
我弱弱的问一下, 你电脑是M1的么

**Comment by Z-fly** [comment]
是黑苹果啊

**Comment by niuhuan** [comment]
为啥我黑苹果11就能用，而且别人都没问题，你有显卡驱动吗

**Comment by Z-fly** [comment]
> 为啥我黑苹果11就能用，而且别人都没问题，你有显卡驱动吗

用的独显，驱动了的
1.0.16没闪退

**Comment by niuhuan** [comment]
母鸡，我跟群里问别人17也不闪退

**Comment by Z-fly** [comment]
➜  ~ /Applications/pikapi.app/Contents/MacOS/pikapi ; exit;
初始化 : /Users/z/Library/Application Support/pikapi

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32
[0.097ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="properties"

2021/09/15 10:01:22 /Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/database/properties/properties.go:25
[0.079ms] [rows:-] SELECT * FROM `properties` LIMIT 1

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:259
[0.030ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "properties" AND name = "idx_properties_deleted_at"

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:259
[0.050ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "properties" AND name = "uk_k"

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32
[0.034ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="network_caches"

2021/09/15 10:01:22 /Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/database/network_cache/cache.go:31
[0.024ms] [rows:-] SELECT * FROM `network_caches` LIMIT 1

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:259
[0.028ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "network_caches" AND name = "idx_network_caches_deleted_at"

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:259
[0.046ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "network_caches" AND name = "uk_k"

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32
[0.032ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="categories"

2021/09/15 10:01:22 /Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/database/comic_center/center.go:24
[0.055ms] [rows:-] SELECT * FROM `categories` LIMIT 1

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:259
[0.033ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "categories" AND name = "idx_categories_deleted_at"

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32
[0.029ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="comic_views"

2021/09/15 10:01:22 /Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/database/comic_center/center.go:25
[0.049ms] [rows:-] SELECT * FROM `comic_views` LIMIT 1

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32
[0.035ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="remote_images"

2021/09/15 10:01:22 /Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/database/comic_center/center.go:26
[0.053ms] [rows:-] SELECT * FROM `remote_images` LIMIT 1

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:259
[0.033ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "remote_images" AND name = "idx_remote_images_deleted_at"

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:259
[0.040ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "remote_images" AND name = "uk_fp"

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32
[0.028ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="comic_downloads"

2021/09/15 10:01:22 /Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/database/comic_center/center.go:27
[0.219ms] [rows:-] SELECT * FROM `comic_downloads` LIMIT 1

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32
[0.045ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="comic_download_eps"

2021/09/15 10:01:22 /Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/database/comic_center/center.go:28
[0.057ms] [rows:-] SELECT * FROM `comic_download_eps` LIMIT 1

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:259
[0.031ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "comic_download_eps" AND name = "idx_comic_id"

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32
[0.025ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="comic_download_pictures"

2021/09/15 10:01:22 /Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/database/comic_center/center.go:29
[0.034ms] [rows:-] SELECT * FROM `comic_download_pictures` LIMIT 1

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:259
[0.033ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "comic_download_pictures" AND name = "idx_comic_id"

2021/09/15 10:01:22 /Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:242 index idx_comic_id already exists
[0.036ms] [rows:0] CREATE INDEX `idx_comic_id` ON `comic_download_pictures`(`comic_id`)

2021/09/15 10:01:22 /Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/database/properties/properties.go:38 record not found
[0.147ms] [rows:0] SELECT * FROM `properties` WHERE `k` = "switch_address" AND `properties`.`deleted_at` IS NULL ORDER BY `properties`.`id` LIMIT 1

2021/09/15 10:01:22 /Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/database/properties/properties.go:38 record not found
[0.063ms] [rows:0] SELECT * FROM `properties` WHERE `k` = "proxy" AND `properties`.`deleted_at` IS NULL ORDER BY `properties`.`id` LIMIT 1

2021/09/15 10:01:22 /Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/database/comic_center/center.go:479
[0.153ms] [rows:0] UPDATE `comic_downloads` SET `download_failed`=false,`updated_at`="2021-09-15 10:01:22.484" WHERE 1 = 1

2021/09/15 10:01:22 /Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/database/comic_center/center.go:484
[0.039ms] [rows:0] UPDATE `comic_download_eps` SET `download_failed`=false,`updated_at`="2021-09-15 10:01:22.484" WHERE 1 = 1

2021/09/15 10:01:22 /Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/database/comic_center/center.go:489
[0.040ms] [rows:0] UPDATE `comic_download_pictures` SET `download_failed`=false WHERE 1 = 1
后台线程启动
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fff203c2928]

runtime stack:
runtime.throw(0x47033ae, 0x2a)
	/Volumes/DATA/RUNTIMES/Go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/Volumes/DATA/RUNTIMES/Go/src/runtime/signal_unix.go:718 +0x2ef

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x44c1790, 0xc00018baf0, 0xc00018bb28)
	/Volumes/DATA/RUNTIMES/Go/src/runtime/cgocall.go:154 +0x5b fp=0xc00018bac0 sp=0xc00018ba88 pc=0x4005adb
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwInit(0x0)
	_cgo_gotypes.go:1398 +0x45 fp=0xc00018baf0 sp=0xc00018bac0 pc=0x44633c5
github.com/go-gl/glfw/v3.3/glfw.Init(0xaaaaaaaaaaaaaaaa, 0x38)
	/Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20201108214237-06ea97f0c265/glfw.go:36 +0x25 fp=0xc00018bb30 sp=0xc00018baf0 pc=0x4466b25
github.com/go-flutter-desktop/go-flutter.(*Application).Run(0xc000104000, 0x0, 0x0)
	/Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.43.0/application.go:90 +0x4a fp=0xc00018bec0 sp=0xc00018bb30 pc=0x449688a
github.com/go-flutter-desktop/go-flutter.Run(0xc00032db00, 0x6, 0x8, 0xc00018bf68, 0x2)
	/Volumes/DATA/RUNTIMES/GoPATH/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.43.0/application.go:26 +0x4d fp=0xc00018bef0 sp=0xc00018bec0 pc=0x4495ead
main.main()
	/Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/cmd/main.go:25 +0x185 fp=0xc00018bf88 sp=0xc00018bef0 pc=0x44a4c25
runtime.main()
	/Volumes/DATA/RUNTIMES/Go/src/runtime/proc.go:225 +0x256 fp=0xc00018bfe0 sp=0xc00018bf88 pc=0x403ac16
runtime.goexit()
	/Volumes/DATA/RUNTIMES/Go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00018bfe8 sp=0xc00018bfe0 pc=0x406e2c1

goroutine 19 [select]:
database/sql.(*DB).connectionOpener(0xc00009fc70, 0x4791f40, 0xc00027a480)
	/Volumes/DATA/RUNTIMES/Go/src/database/sql/sql.go:1133 +0xb5
created by database/sql.OpenDB
	/Volumes/DATA/RUNTIMES/Go/src/database/sql/sql.go:740 +0x12a

goroutine 20 [select]:
database/sql.(*DB).connectionOpener(0xc000301ad0, 0x4791f40, 0xc00027b640)
	/Volumes/DATA/RUNTIMES/Go/src/database/sql/sql.go:1133 +0xb5
created by database/sql.OpenDB
	/Volumes/DATA/RUNTIMES/Go/src/database/sql/sql.go:740 +0x12a

goroutine 21 [select]:
database/sql.(*DB).connectionOpener(0xc000321860, 0x4791f40, 0xc00032c800)
	/Volumes/DATA/RUNTIMES/Go/src/database/sql/sql.go:1133 +0xb5
created by database/sql.OpenDB
	/Volumes/DATA/RUNTIMES/Go/src/database/sql/sql.go:740 +0x12a

goroutine 34 [sleep]:
time.Sleep(0xb2d05e00)
	/Volumes/DATA/RUNTIMES/Go/src/runtime/time.go:193 +0xd2
pgo/pikapi/controller.downloadBegin()
	/Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/controller/download.go:27 +0x2b
created by pgo/pikapi/controller.downloadBackground
	/Volumes/DATA/PROJECTS/Flutter/pikapi-golang/go/pikapi/controller/download.go:23 +0x5d
Saving session...completed.

**Comment by Z-fly** [comment]
flutter应该不支持10.7

Process:         launchd [434]
Path:            /Users/USER/Desktop/pikapi.app/Contents/MacOS/pikapi
Identifier:      com.pikapi.pikapi
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [139]

Date/Time:       2021-09-15 10:09:08.491 +0800
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          1563 sec
Crashes Since Last Report:           5
Per-App Crashes Since Last Report:   3
Anonymous UUID:                      A991AD8B-84BB-477B-94EB-DF133BAC70BD

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 1

Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 308
    thread_create: 0
    thread_set_state: 0

Model: Parallels17,1, BootROM 17.0.1 (51482), 2 processors, 3 GHz, 2 GB, SMC 1.16f8
Graphics: Display, PCI, 32 MB
Memory Module: BANK #0/DIMM #0, 2 GB, DRAM, 667 MHz, Parallels Virtual RAM, PRL-2048MB
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: Virtual HDD, 137.44 GB
Serial ATA Device: Virtual DVD-ROM [1]
USB Device: Virtual Mouse, 0x203a, 0xfffc, 0xdd900000 / 1
USB Device: Virtual Printer (EPSON L365 Series), 0x203a, 0xfffa, 0xfd300000 / 2
USB Device: Virtual Keyboard, apple_vendor_id, 0x024f, 0x1d100000 / 2

**Comment by niuhuan** [comment]
如果最新版你还闪退，……换个白苹果或者更新下系统

**Comment by Z-fly** [comment]
> 如果最新版你还闪退，……换个白苹果或者更新下系统

我之后再试试。
话说解除封印的功能可以加吗？

**Comment by niuhuan** [comment]
封印/解除封印的功能早就有了好嘛, 设置里面

**Comment by Z-fly** [comment]
> 封印/解除封印的功能早就有了好嘛, 设置里面

能不能像哔咔那样，在栏目界面加个按钮 点击解除封印 再点击封印

**Comment by niuhuan** [comment]
> > 封印/解除封印的功能早就有了好嘛, 设置里面
> 
> 能不能像哔咔那样，在栏目界面加个按钮 点击解除封印 再点击封印

能
