### ISSUE TITLE
Run at 60hz on OnePlus 8P

### ISSUE THREAD

**Issue by ShiinaManatsu** [niuhuan/pikapi-flutter#27]
有个启用120hz的包希望可以加入以支持120hz刷新率

**Comment by niuhuan** [comment]
你可以下载新的Release, 到设置中看一下, 可以切换DisplayMode (刷新率). 我没有1+手机, 我不知道这会不会达到预期效果。

**Comment by Z-fly** [comment]
iPhone 13也有120HZ 不知道能否在软件里实现

**Comment by Z-fly** [comment]
@niuhuan 安卓最高可以设置144hz吗？

**Comment by ShiinaManatsu** [comment]
> @niuhuan 安卓最高可以设置144hz吗？

https://pub.dev/packages/flutter_displaymode
我的1+8P可以, iPhone13出来的时候这个插件还没更新难说(

**Comment by Z-fly** [comment]
> > @niuhuan 安卓最高可以设置144hz吗？
> 
> https://pub.dev/packages/flutter_displaymode
> 我的1+8P可以, iPhone13出来的时候这个插件还没更新难说(

是超频到144吗？

**Comment by niuhuan** [comment]
> > @niuhuan 安卓最高可以设置144hz吗？
> 
> https://pub.dev/packages/flutter_displaymode
> 我的1+8P可以, iPhone13出来的时候这个插件还没更新难说(

我看他源码里引用的一些api过时了，参照这个和安卓官方api写的，原理应该一样。

**Comment by niuhuan** [comment]
> @niuhuan 安卓最高可以设置144hz吗？

@Z-fly 

![Screenshot_20210924-202716](https://user-images.githubusercontent.com/20847533/134674201-e30d7e67-01e2-4073-b067-ce3ab6528928.jpg)

能列出你手机支持的所有刷新频率，并选择一个。

**Comment by niuhuan** [comment]
> iPhone 13也有120HZ 不知道能否在软件里实现

没钱，所以不能实现。

**Comment by Z-fly** [comment]
Xcode有模拟器，不知道能否模拟出来

**Comment by niuhuan** [comment]
> Xcode有模拟器，不知道能否模拟出来

你有没有用高刷新频率的手机试一下, 我还不知道结果。

**Comment by Z-fly** [comment]
我也买不起苹果，我手里的安卓确实可以120hz，效果可以的
