### ISSUE TITLE
进度条不能隐藏起来吗？

### ISSUE THREAD

**Issue by Z-fly** [niuhuan/pikapi-flutter#30]
加个选项，保持进度条一直显示/手动移动漫画时显示进度条/隐藏进度条

**Comment by Z-fly** [comment]
哦，是BUG。安卓无法隐藏进度条了。

**Comment by Z-fly** [comment]
https://user-images.githubusercontent.com/10470892/134690122-4e5fa714-88d2-4954-92cc-72045e37f09f.mp4

**Comment by Z-fly** [comment]
我调了一下，又显示不出进度条了

**Comment by Z-fly** [comment]
最新版给改坏掉了 
太草了

**Comment by niuhuan** [comment]
flutter state 的问题，连夜改了10行代码。你看能用了不。
