### ISSUE TITLE
【BUG】窗口初始化有问题

### ISSUE THREAD

**Issue by Z-fly** [niuhuan/pikapi-flutter#31]
https://user-images.githubusercontent.com/10470892/134776089-f7d50ba5-9791-4ece-9600-82f0f64dbee5.mp4

**Comment by Z-fly** [comment]
你窗口初始化可以做个自适应缩放居中吗？

**Comment by Z-fly** [comment]
还有那个全分类，建议你改成这样：最近更新(全分类) 
更符合原版哔咔用户的习惯

**Comment by niuhuan** [comment]
现在是固定大小初始化的, 我感觉得想办法保存一下用户的窗口大小。 所有的分类排序都是最近更新, 然后右上角调节。

**Comment by niuhuan** [comment]
已经保存上次的窗口大小了

**Comment by Z-fly** [comment]
那能否做成第一次打开时候 自适应居中
