### ISSUE TITLE
收到哔咔官方的函了吗？

### ISSUE THREAD

**Issue by Z-fly** [niuhuan/pikapi-flutter#34]
Releases全部撤掉了

**Comment by niuhuan** [comment]
本App跟哔咔没有关系

**Comment by niuhuan** [comment]
项目在重构，距离下次Release有一些时间

**Comment by Z-fly** [comment]
https://github.com/AnkiKong/picacomic/issues/14

好多相关仓库被发函了，可能哔咔要改api了

**Comment by niuhuan** [comment]
> [AnkiKong/picacomic#14](https://github.com/AnkiKong/picacomic/issues/14)
> 
> 好多相关仓库被发函了，可能哔咔要改api了

或许是好事，一个平台活下来。还有本子看。
