### ISSUE TITLE
[Bug]在我的-配置选项中“返回”会直接退出软件

### ISSUE THREAD

**Issue by zhongfly** [niuhuan/pikapi-flutter#4]
软件版本：android 1.0.3
复现步骤：
1.正常登录进入软件
2.点击“我的”，右上角“配置选项”
3.按手机返回键，直接退出了软件而非返回到“我的”

另外建议，退出软件需二次确认(比如toast提醒需要连按2次返回键，或者弹窗确认)，并增加设置可以关闭二次确认

**Comment by niuhuan** [comment]
在“配置选项”中直接退出应用, 软件是故意这么设计的, 因为更新账户后会清空登录信息, 再返回 “我的”, 接口将不能使用。

**Comment by zhongfly** [comment]
> 在“配置选项”中直接退出应用, 软件是故意这么设计的, 因为更新账户后会清空登录信息, 再返回 “我的”, 接口将不能使用。

我觉得如果是这个原因不如改成重启软件？
二次确认或者提醒是有必要的，否则就会觉得发生了闪退，与用户预期不同
