### ISSUE TITLE
iOS版本安装

### ISSUE THREAD

**Issue by AlanDinkle** [niuhuan/pikapi-flutter#5]
请问有没有ios版本安装教程呀，求指一条路(((o(*ﾟ▽ﾟ*)o)))

**Comment by zhongfly** [comment]
ios的可以试试https://github.com/fanyuecheng/Pica

**Comment by AlanDinkle** [comment]
> ios的可以试试https://github.com/fanyuecheng/Pica

谢谢(*°∀°)=3
