### ISSUE TITLE
离线使用反馈

### ISSUE THREAD

**Issue by Jacheers** [niuhuan/pikapi-flutter#50]
既然看过的本子会缓存在本地，那离线打开pikapi的浏览记录时，应该可以看已缓存的本子才对，而不是傻傻地提示用户下拉刷新。
顺带一提，已缓存的本子在下载时可以直接从remote文件夹提取图片，就不必再下载一次。

**Comment by Jacheers** [comment]
抱歉迟了，需求确实是像你说的那样。

**Comment by Z-fly** [comment]
> 多加个控制选项吧。感觉明知有缓存，前端却又无法显示，就挺难受的。

有必要加个控制开关吗，离线模式上不了网的话，只能读缓存

**Comment by Jacheers** [comment]
就是因为读不了缓存啊。明明图片可以缓存一个月，但漫画信息2个小时就没了，导致2个小时以后的漫画都加载不出来。

**Comment by niuhuan** [comment]
如果没有网, 可能会卡在登录页面, 也有可能已经进入了app才离线的。

入口放在哪里, 怎么退出还是要考虑, 这个场景用的比较少, 最好不影响其他用户体验。

 (反复要看的内容为什么不用下载呢, 我会先做多线程/多携程下载的功能)。
