### ISSUE TITLE
疑似无法登录

### ISSUE THREAD

**Issue by zhongfly** [niuhuan/pikapi-flutter#55]
我已确认账号密码正确，在官方版本上用完全相同的账号密码重新登录成功。
联想到多日前的服务器维护，是否可能是服务器会检查版本号？
其他客户端使用2.2.1.3.3.4的版本号登录正常
以下为官方最新版本的登录请求：
```
POST /auth/sign-in h2 
Host: picaapi.picacomic.com 
api-key: C69BAF41DA5ABD1FFEDC6D2FEA56B 
accept: application/vnd.picacomic.com.v1+json 
app-channel: 2 
time: 1635686069 
nonce: 78e0badd1e6145c1bc5334e5899fef6c 
signature: 7f9fb11fd3f46ef40013e5296afdac140ab020687530f43cd98bd4d15dd14a28 
app-version: 2.2.1.3.3.4 
app-uuid: defaultUuid 
image-quality: original 
app-platform: android 
app-build-version: 45 
content-type: application/json; charset=UTF-8 
content-length: 43 
accept-encoding: gzip 
user-agent: okhttp/3.8.1 
 
{"email":" ","password":" "}
```

**Comment by niuhuan** [comment]
看到你的消息后，我用分流2登陆成功，请检查你的代理或者分流，或者账号密码，现在新版也会有登录的错误信息，也可以截图或把message发给我。

**Comment by zhongfly** [comment]
也有可能是服务器不稳，我在官方版再次登录提示“xxxx被玩坏了”即服务器故障

**Comment by niuhuan** [comment]
我前两天遇到过使用4G网络无法访问，代理或者Wifi后恢复正常，应该只是网络原因

**Comment by niuhuan** [comment]
我最近在弄那个小程序，我发现官方app没有办法抓包，他的httpclient和webview不信任手机的vpn证书，导致minitproxy抓不到包。你有方法吗？

**Comment by zhongfly** [comment]
> 我最近在弄那个小程序，我发现官方app没有办法抓包，他的httpclient和webview不信任手机的vpn证书，导致minitproxy抓不到包。你有方法吗？

我是用httpcanary抓的，不过有时候又失灵
