### ISSUE TITLE
hover run 报错

### ISSUE THREAD

**Issue by jwguo321** [niuhuan/pikapi-flutter#6]
尝试自己编译Mac版，结果出现以下错误
hover: Using engine from cache
hover: Cleaning the build directory
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Bundling flutter app

💪 Building with sound null safety 💪

hover: Compiling 'go-flutter' and plugins
go: pica@v0.0.0 (replaced by ./pica): reading pica/go.mod: open /Users/myname/pikapi-flutter/go/pica/go.mod: no such file or directory
hover: Go build failed: exit status 1
===================================
go version: 1.16.7
hover version: v0.46.6
flutter SDK: 2.2.3

**Comment by niuhuan** [comment]
WARNING 的消除: The go-flutter project tries to stay compatible with the beta channel of Flutter. 执行 flutter channel beta ,将flutter设置为beta版本 , 随着flutter的更新, 这已经不是必须选项

ERROR 的消除 :no such file or directory , 这是因为在克隆仓库时您没有克隆submodule。 您应该使用 git clone --recursive $仓库地址 , 这样/go/pica/go.mod将会被同时克隆。

由于打包比较繁琐,  我在 releases 中上传了适用于mac的.dmg文件, 您可以直接下载运行。

**Comment by jwguo321** [comment]
> WARNING 的消除: The go-flutter project tries to stay compatible with the beta channel of Flutter. 执行 flutter channel beta ,将flutter设置为beta版本 , 随着flutter的更新, 这已经不是必须选项
> 
> ERROR 的消除 :no such file or directory , 这是因为在克隆仓库时您没有克隆submodule。 您应该使用 git clone --recursive $仓库地址 , 这样/go/pica/go.mod将会被同时克隆。
> 
> 由于打包比较繁琐, 我在 releases 中上传了适用于mac的.dmg文件, 您可以直接下载运行。



> WARNING 的消除: The go-flutter project tries to stay compatible with the beta channel of Flutter. 执行 flutter channel beta ,将flutter设置为beta版本 , 随着flutter的更新, 这已经不是必须选项
> 
> ERROR 的消除 :no such file or directory , 这是因为在克隆仓库时您没有克隆submodule。 您应该使用 git clone --recursive $仓库地址 , 这样/go/pica/go.mod将会被同时克隆。
> 
> 由于打包比较繁琐, 我在 releases 中上传了适用于mac的.dmg文件, 您可以直接下载运行。

好的，已经下载dmg包，非常感谢🙏
