### ISSUE TITLE
Android端阅读漫画时无法对图片进行缩放

### ISSUE THREAD

**Issue by hazyKam** [niuhuan/pikapi-flutter#7]
- 希望可以增加双击和双指缩放的功能，个别漫画字太小，不放大实在看不清。

**Comment by niuhuan** [comment]
您可以下载 pre-release V1.0.6._p1。

增加了以下功能:
1. 在阅读器中。 图片加载完成后, 长按图片后选择预览, 对当张图片进行缩放。

-----
点按屏幕后进入全屏阅读, 和点击图片放大的需求是冲突的, 您如果有想法可以提出建议。

**Comment by zhongfly** [comment]
> 您可以下载 pre-release V1.0.6._p1。
> 
> 增加了以下功能:
> 
> 1. 在阅读器中。 图片加载完成后, 长按图片后选择预览, 对当张图片进行缩放。
> 
> 点按屏幕后进入全屏阅读, 和点击图片放大的需求是冲突的, 您如果有想法可以提出建议。

可以分成单击和双击（或双指缩放）操作，单击全屏，双击（或双指缩放）放大，这不是冲突的

**Comment by niuhuan** [comment]
现在放大是长按图片后进入新的页面单独进行缩放。如果直接在阅读器上放大缩小就缩放了整个阅读器, 或者缩放了所有图片, 这样也不友好。

可以做成长按缩放, 单击切换全屏, 众口难调是个问题。

**Comment by zhongfly** [comment]
> 现在放大是长按图片后进入新的页面单独进行缩放。如果直接在阅读器上放大缩小就缩放了整个阅读器, 或者缩放了所有图片, 这样也不友好。
> 
> 可以做成长按缩放, 单击切换全屏, 众口难调是个问题。

缩放所有图片是正常的啊，我用过的漫画阅读软件里，如果是处于pika目前这种从上到下连续的模式，缩放时就是所有图片都缩放。只有翻页阅读（屏幕只显示一页图片）时，才是只缩放当前图片

**Comment by niuhuan** [comment]
> > 现在放大是长按图片后进入新的页面单独进行缩放。如果直接在阅读器上放大缩小就缩放了整个阅读器, 或者缩放了所有图片, 这样也不友好。
> > 可以做成长按缩放, 单击切换全屏, 众口难调是个问题。
> 
> 缩放所有图片是正常的啊，我用过的漫画阅读软件里，如果是处于pika目前这种从上到下连续的模式，双击缩放时就是所有图片都缩放。只有翻页阅读（屏幕只显示一页图片）时，才是只缩放当前图片。（建议作者尝试体验一下[tachiyomi](https://tachiyomi.org/)这个app里的webtoon阅读模式，就是pika目前这种阅读模式）
> 只要操作方便，图片放大或恢复原样都是很简单的操作时，会不会缩放所有图片根本就是小事，因为一下就切换回去了。
> 如果是需要多步操作（长按图片-再操作缩放），那实在不够方便

体验了一下这个阅读器，Webtoon模式简直不要太棒，还有好多代码要写。

**Comment by hazyKam** [comment]
> > 缩放所有图片是正常的啊，我用过的漫画阅读软件里，如果是处于pika目前这种从上到下连续的模式，双击缩放时就是所有图片都缩放。只有翻页阅读（屏幕只显示一页图片）时，才是只缩放当前图片。（建议作者尝试体验一下[tachiyomi](https://tachiyomi.org/)这个app里的webtoon阅读模式，就是pika目前这种阅读模式）
> > 只要操作方便，图片放大或恢复原样都是很简单的操作时，会不会缩放所有图片根本就是小事，因为一下就切换回去了。
> > 如果是需要多步操作（长按图片-再操作缩放），那实在不够方便
> 
> 体验了一下这个阅读器，Webtoon模式简直不要太棒，还有好多代码要写。

感谢开发者的回复和zhongfly老哥的补全描述，zhongfly老哥回复中所说就是我想表达的实现方式。👍

**Comment by niuhuan** [comment]
@zhongfly  @hazyKam  做了很多尝试和考察

---

哔咔是如何实现的

哔咔的webtoon放大模式, 将图片分成若干页, 每页初始化了若干张图片, 拼成一个组件, 从而实现了拖拽,  因为拼成了一个组件, 所以一开始就会初始化所有的片, 为了内存管理, 必然会阅读几张图片然后就需要翻页。

---

pikapi现状

pikapi的翻页模式, 滚动后图片会内存回收, 能一直持续翻页, 但是不能放大。没有找到放大解决方案, 自定义组件, 状态和手势管理也要做, 这将是个困难而又漫长的过程。

----

解决方案


给阅读器增加多种阅读模式, 增加哔咔这种, 保留现有这种, 将来再加入翻页模式, 会不会比较好。

**Comment by zhongfly** [comment]
> @zhongfly @hazyKam 做了很多尝试和考察
> 
> 哔咔是如何实现的
> 
> 哔咔的webtoon放大模式, 将图片分成若干页, 每页初始化了若干张图片, 拼成一个组件, 从而实现了拖拽, 因为拼成了一个组件, 所以一开始就会初始化所有的片, 为了内存管理, 必然会阅读几张图片然后就需要翻页。
> 
> pikapi现状
> 
> pikapi的翻页模式, 滚动后图片会内存回收, 能一直持续翻页, 但是不能放大。没有找到放大解决方案, 自定义组件, 状态和手势管理也要做, 这将是个困难而又漫长的过程。
> 
> 解决方案
> 
> 给阅读器增加多种阅读模式, 增加哔咔这种, 保留现有这种, 将来再加入翻页模式, 会不会比较好。

试了下WebToon + 分页 + 双击放大 (试验性)，这个感觉不好用，必须点下一页才能继续阅读…
之前的webtoon+双击放大感觉不错

**Comment by niuhuan** [comment]
“之前的webtoon+双击放大“   其实双击放大的组件和滚动组件有冲突,  会造成滑动条不准, 就去掉了。

可以改成懒加载就不必须点下一页了, 这样, 体验就接近哔咔了。 它的APP就不能跨页滚动。

**Comment by niuhuan** [comment]
应该是解决了, 在阅读器里面设置下双击缩放就好了

**Comment by zhongfly** [comment]
> 应该是解决了, 在阅读器里面设置下双击缩放就好了

不错了～希望增加单击进入全屏模式，并且可以默认打开就是全屏

**Comment by zhongfly** [comment]
> 应该是解决了, 在阅读器里面设置下双击缩放就好了

双击缩放有一个问题，放大后不能图片左右移动了，导致看不到放大后左右两侧的内容

**Comment by niuhuan** [comment]
缩放组件和拖动控件互斥, 缩放的时候, 我屏蔽了一下滚动手势, 现在应该可以了, 但是缩放状态下无法滚动

**Comment by zhongfly** [comment]
> 缩放组件和拖动控件互斥, 缩放的时候, 我屏蔽了一下滚动手势, 现在应该可以了, 但是缩放状态下无法滚动

只能说目前这样没有达到我的预期……
