### ISSUE TITLE
[建议]使用Github Action来自动化编译

### ISSUE THREAD

**Issue by zhongfly** [niuhuan/pikapi-flutter#8]
[参见文档](https://docs.github.com/cn/actions/learn-github-actions/introduction-to-github-actions)，Github Action可以方便的进行自动化编译，例如增加新commit时自动编译打包各个平台的软件并发布到release，节约开发者的时间，也方便用户直接测试。
比如我自己为了直接使用最新版，就写了编译pika的[ation流程](https://github.com/zhongfly/apk-Build/blob/main/.github/workflows/PIKAPI.yml)。
只是个人的一些建议

**Comment by JONREAN2** [comment]
上传到哪里了？ 有木有更详细介绍啊...... 想搞一个ios的，拜求大佬指点

**Comment by zhongfly** [comment]
> 上传到哪里了？ 有木有更详细介绍啊...... 想搞一个ios的，拜求大佬指点

我不了解ios版本怎么编译…你看https://github.com/niuhuan/pikapi-flutter/issues/14 吧。

**Comment by JONREAN2** [comment]
哪可以说一下怎么使用你的action吗？ac里面的secret咋填啊

**Comment by zhongfly** [comment]
> 哪可以说一下怎么使用你的action吗？ac里面的secret咋填啊

需要有一定github action使用经验和简单的安卓应用开发知识，secret需要什么内容参见
https://github.com/r0adkll/sign-android-release

**Comment by JONREAN2** [comment]
收到 多谢了

**Comment by niuhuan** [comment]
增加了一个UI全屏的功能

**Comment by aaaly666** [comment]
对于不懂这些的想用pikapi，没有安卓的包，该咋搞
