### ISSUE TITLE
Windows下无法显示图标

### ISSUE THREAD

**Issue by ryank231231** [niuhuan/pikapi-flutter#9]
![image](https://user-images.githubusercontent.com/5959659/129061835-b7d537e8-6ffb-484d-a21f-62a0e7e0a233.png)

OS:Windows 10 Build 19042

**Comment by niuhuan** [comment]
我的windows版本更高一些，没有发现这个问题 emmm

![QQ截图20210812091315](https://user-images.githubusercontent.com/20847533/129123361-5421af38-1a03-4563-809b-8a6c482bb106.png)

字体在 程序目录的flutter_assets\fonts文件夹，您检查一下文件是否存在，或者安装一下字体（一般是不需要安装的）。

**Comment by ryank231231** [comment]
疑似是NTFS权限造成的问题。。
换了个盘符后一切正常
![image](https://user-images.githubusercontent.com/5959659/129139073-38474fe9-463a-4083-9a78-d122a3617a2a.png)
